// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2SOjgTb0Wcfk1xvvgjxO_CHzEsqCnABo',
    appId: '1:597106120528:web:015b6252dd0c8a3165be55',
    messagingSenderId: '597106120528',
    projectId: 'kyukimemo',
    authDomain: 'kyukimemo.firebaseapp.com',
    storageBucket: 'kyukimemo.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlLvBwmK08eHwwTw28Tg1Ix2wVzQxKpio',
    appId: '1:597106120528:android:21aadd751e598c5365be55',
    messagingSenderId: '597106120528',
    projectId: 'kyukimemo',
    storageBucket: 'kyukimemo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAd_iCGZ6uCRZC5iRkGWbxlRedbFNkkP-8',
    appId: '1:597106120528:ios:5c3a5b49ba0fd09065be55',
    messagingSenderId: '597106120528',
    projectId: 'kyukimemo',
    storageBucket: 'kyukimemo.appspot.com',
    iosClientId: '597106120528-p8un1lt5298ek8vaqpikeis1aq4c1ebv.apps.googleusercontent.com',
    iosBundleId: 'com.kyuki3rain.yukimemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAd_iCGZ6uCRZC5iRkGWbxlRedbFNkkP-8',
    appId: '1:597106120528:ios:5c3a5b49ba0fd09065be55',
    messagingSenderId: '597106120528',
    projectId: 'kyukimemo',
    storageBucket: 'kyukimemo.appspot.com',
    iosClientId: '597106120528-p8un1lt5298ek8vaqpikeis1aq4c1ebv.apps.googleusercontent.com',
    iosBundleId: 'com.kyuki3rain.yukimemo',
  );
}
